# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgis
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gis
  username: postgres
  host: localhost
  schema_search_path: public
