# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d93f01a2eb20255838f3fbe20c33e88888a99676fd8652f7fd5a680336820eac6ab95e5e38f24d4f0bf149e3eed763681d85ef22fffc533c6263f7226070ad06

test:
  secret_key_base: e28aa08cfffc5a33d69e61665f8fcb67e6da95d5c97781f54e3a59606af9f1be6d282cca3ad3e3c3547877c9f909fca373a819d6f3c53845fa51050301414599

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
